### ISSUE TITLE
Show views

### ISSUE THREAD

**Issue by GerardoSuarezRamos** [kiddae/dotfiles#2]
I like see pictures about your configuration, current use neovim with Windows 10 and Windows terminal, however, I have virtual machine running Arch Linux with Qtile.

**Comment by kiddae** [comment]
Hello,
I will create another issue to put screenshot and informations about my setup. 
However keep in mind that I use `bspwm` so you won't be able to replicate it with `qtile`. If have other repositories mainly for my [polybar themes](https://github.com/ngynLk/polybar-themes), and you won't find anything really special in this repository (I made it for myself initially)
