### ISSUE TITLE
Recommended DE?

### ISSUE THREAD

**Issue by DznDani** [kiddae/dotfiles#7]
This is a really dumb question but, im coming back to arch linux again (to finally use it long term i guess?), and i really liked the themes, but i don't know what desktop environment is recommended for this so i would like to know...

Sorry for bad english :L

**Comment by kiddae** [comment]
Hi,
All of it is `bspwm`, with the configuration for it included in every theme. I haven't used anything else in a while.

**Comment by DznDani** [comment]
Oh wow, well so i will have to figure it out, thanks!
